In [1]:
#Quaternion Calculator
import numpy as np
alfa=-90*3.14/180
beta=120*3.14/180
gamma=45*3.14/180

In [10]:
R=np.array([[np.cos(alfa)*np.cos(beta)*np.cos(gamma)-np.sin(alfa)*np.sin(gamma)
           ,-np.cos(alfa)*np.cos(beta)*np.sin(gamma)-np.sin(alfa)*np.cos(gamma)
           ,np.cos(alfa)*np.sin(beta)],
            
           [np.sin(alfa)*np.cos(beta)*np.cos(gamma)+np.cos(alfa)*np.sin(gamma)
           ,-np.sin(alfa)*np.cos(beta)*np.sin(gamma)+np.cos(alfa)*np.cos(gamma)
           ,np.sin(alfa)*np.sin(beta)],
            
           [-np.sin(beta)*np.cos(gamma)
           ,np.sin(beta)*np.sin(gamma)
           ,np.cos(beta)]])

In [4]:
R

array([[-0.92333571,  0.21127298, -0.32064761],
       [-0.21127298,  0.41776968,  0.88364711],
       [ 0.32064761,  0.88364711, -0.34110539]])

In [22]:

gamma=-120*3.14/180
R1=np.array([[1,0,0],
           [0,np.cos(gamma),-np.sin(gamma)],
           [0,np.sin(gamma),np.cos(gamma)]])
R1

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       , -0.4990802,  0.8665558],
       [ 0.       , -0.8665558, -0.4990802]])

In [26]:

beta=-90*3.14/180
R2=np.array([[np.cos(beta),1,np.sin(beta)],
           [0,1,0],
           [-np.sin(beta),1,np.cos(beta)]])
R2

array([[ 7.96326711e-04,  1.00000000e+00,  9.99999683e-01],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-9.99999683e-01,  1.00000000e+00,  7.96326711e-04]])

In [4]:

alfa=-90*3.14/180
R3=np.array([[np.cos(alfa),-np.sin(alfa),0],
           [np.sin(alfa),np.cos(alfa),0],
           [0,0,1]])
R3

array([[ 7.96326711e-04, -9.99999683e-01,  0.00000000e+00],
       [ 9.99999683e-01,  7.96326711e-04,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [27]:
R=R2

In [30]:
q0=0.5*np.sqrt(1+R[0,0]+R[1,1]+R[2,2])

inv_q0=1/(4*q0)

q1=inv_q0*(R[2,1]-R[1,2])

q2=inv_q0*(R[0,2]-R[2,0])

q3=inv_q0*(R[1,0]-R[0,1])

In [31]:
"{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"}"

'{x:0.3534127026086002, y:0.7068251811053659, z:-0.3534127026086002, w:0.7073882691671998}'

In [123]:
"[{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"},"+"{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"},"+"{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"},"+"{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"},"+"{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"}]"

'[{x:-0.13734020565221053, y:0.23373363509781336, z:-0.6204835244747892, w:0.7358712194336143},{x:-0.13734020565221053, y:0.23373363509781336, z:-0.6204835244747892, w:0.7358712194336143},{x:-0.13734020565221053, y:0.23373363509781336, z:-0.6204835244747892, w:0.7358712194336143},{x:-0.13734020565221053, y:0.23373363509781336, z:-0.6204835244747892, w:0.7358712194336143},{x:-0.13734020565221053, y:0.23373363509781336, z:-0.6204835244747892, w:0.7358712194336143}]'

In [253]:

rot_x=np.cos(gamma/2)+np.sin(gamma/2)

"{x:"+str(rot_x)+", "+"y:"+str(0)+", "+"z:"+str(0)+", "+"w:"+str(np.cos(gamma/2))+"}"

'{x:-0.8337801742052777, y:0, z:0, w:0.15425144988758405}'

In [249]:

rot_y=np.cos(beta/2)+np.sin(beta/2)

"{x:"+str(0)+", "+"y:"+str(rot_y)+", "+"z:"+str(0)+", "+"w:"+str(np.cos(beta/2))+"}"

'{x:0, y:-0.8337801742052777, z:0, w:0}'

In [250]:

rot_z=np.cos(alfa/2)+np.sin(alfa/2)

"{x:"+str(0)+", "+"y:"+str(0)+", "+"z:"+str(rot_z)+", "+"w:"+str(np.cos(alfa/2))+"}"

'{x:0, y:0, z:1.0, w:0}'

In [136]:

alfa=0*3.14/180 #X
beta=-30*3.14/180 #Y
gamma=60*3.14/180 #Z

q1 = np.sin(gamma/2) * np.cos(beta/2) * np.cos(alfa/2) - np.cos(gamma/2) * np.sin(beta/2) * np.sin(alfa/2)
q2 = np.cos(gamma/2) * np.sin(beta/2) * np.cos(alfa/2) + np.sin(gamma/2) * np.cos(beta/2) * np.sin(alfa/2)
q3 = np.cos(gamma/2) * np.cos(beta/2) * np.sin(alfa/2) - np.sin(gamma/2) * np.sin(beta/2) * np.cos(alfa/2)
q0 = np.cos(gamma/2) * np.cos(beta/2) * np.cos(alfa/2) + np.sin(gamma/2) * np.sin(beta/2) * np.sin(alfa/2)


In [137]:
"{x:"+str(q1)+", "+"y:"+str(q2)+", "+"z:"+str(q3)+", "+"w:"+str(q0)+"}"

'{x:0.48275801257958395, y:-0.22406716852578193, z:0.12928594968559942, w:0.8366742188527992}'

In [74]:
x= -0.609999000149975006
y=0.0
z=0
w=0.79

np.sqrt(x*x+y*y+z*z+w*w)

0.9980975804919925